pipeline:
  identifier: Build_AskXclaim_child_contact_centre_1790696704771
  name: Vine Child Contact Centre CI
  orgIdentifier: default
  projectIdentifier: Vine_Contact_Centre
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1790696417204
        repoName: AskXclaim/child-contact-centre
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
